test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,27 +1,27 @@
 ---
-name: test
+name: deploy
 on:
-  pull_request: {}
   push:
-    branches:
+    paths:
       - main
 jobs:
-  foo:
-    runs-on: ubuntu-24.04
+  fmt:
+    name: Check if code is formatted
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v4
         with:
           persist-credentials: false
-      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
+      - uses: aquaproj/aqua-installer@v3.1.1
         with:
-          path: ~/.local/share/aquaproj-aqua
-          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua/*.yaml')}}
-          restore-keys: |
-            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
-      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
-        with:
-          aqua_version: v2.34.0
-        env:
-          GITHUB_TOKEN: ${{github.token}}
-      - run: actionlint -version
-      - run: ghalint -v
+          aqua_version: v2.43.0
+      - name: Install gofumpt
+        run: gofumpt -version
+      - name: Check if code is formatted
+        run: |
+          git ls-files | grep -E "\.go$" | xargs gofumpt -l -w
+          if ! git diff --quiet; then
+            echo "::error:: Code isn't formatted. Please format code using gofumpt"
+            exit 1
+          fi
